name: Bump Version & Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Tipo di bump (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: MeilCli/bump-release-action@v2
        with:
          config_path: '.github/bump.yml'
          bump: ${{ github.event.inputs.bump }}
